# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 14:35
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True)),
                ('api_id', models.UUIDField(default=uuid.uuid4)),
                ('api_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookAdAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web Site'), ('canvas', 'Canvas App')], max_length=32)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=False)),
                ('validation', models.CharField(blank=True, max_length=500)),
                ('objective', models.CharField(default='LINK_CLICKS', max_length=100)),
                ('is_reporting_only', models.BooleanField(default=True)),
                ('is_auto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100, unique=True)),
                ('app_secret', fernet_fields.fields.EncryptedCharField(max_length=100)),
                ('access_token', fernet_fields.fields.EncryptedCharField(max_length=256)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('business_id', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shsql.Company')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shsql.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='facebookadaccount',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='shsql.FacebookApp'),
        ),
        migrations.AlterUniqueTogether(
            name='facebookadaccount',
            unique_together=set([('account_id', 'app')]),
        ),
    ]
