# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 20:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccountDailyRawReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbdailyrawreports', to='shsql.FacebookAdAccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbdailyrawreports', to='shsql.Company')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='facebookaccountdailyrawreport',
            unique_together=set([('company', 'account', 'report_date')]),
        ),
    ]
