# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 15:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0002_auto_20170830_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=128)),
                ('level', models.CharField(max_length=128)),
                ('breakdown', models.CharField(max_length=128)),
                ('period', models.PositiveSmallIntegerField(default=1)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shsql.Company')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reportconfig',
            unique_together=set([('platform', 'level', 'breakdown', 'period', 'company')]),
        ),
    ]
