# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0003_auto_20170831_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfig',
            name='breakdown',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
