# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 19:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0004_auto_20170831_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookRawReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbrawreports', to='shsql.FacebookAdAccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbrawreports', to='shsql.Company')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbrawreports', to='shsql.ReportConfig')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='facebookaccountdailyrawreport',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='facebookaccountdailyrawreport',
            name='account',
        ),
        migrations.RemoveField(
            model_name='facebookaccountdailyrawreport',
            name='company',
        ),
        migrations.DeleteModel(
            name='FacebookAccountDailyRawReport',
        ),
        migrations.AlterUniqueTogether(
            name='facebookrawreport',
            unique_together=set([('company', 'account', 'report_date', 'config')]),
        ),
    ]
