# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 20:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0005_auto_20170831_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=128)),
                ('dashboard', models.CharField(max_length=128)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=128)),
                ('dashboard', models.CharField(max_length=128)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashconfigs', to='shsql.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TableConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=128)),
                ('dashboard', models.CharField(max_length=128)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tableconfig',
            unique_together=set([('table', 'dashboard')]),
        ),
        migrations.AlterUniqueTogether(
            name='chartconfig',
            unique_together=set([('field', 'dashboard')]),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardconfig',
            unique_together=set([('company', 'platform', 'dashboard')]),
        ),
    ]
