# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-01 13:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0006_auto_20170831_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookDashboardReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbreports', to='shsql.FacebookAdAccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbreports', to='shsql.Company')),
                ('raw_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbreports', to='shsql.FacebookRawReport')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='facebookdashboardreport',
            unique_together=set([('company', 'account', 'report_date', 'raw_report')]),
        ),
    ]
