# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-01 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0007_auto_20170901_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartconfig',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chartconfigs', to='shsql.Company'),
        ),
        migrations.AddField(
            model_name='tableconfig',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tableconfigs', to='shsql.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='chartconfig',
            unique_together=set([('company', 'field', 'dashboard')]),
        ),
        migrations.AlterUniqueTogether(
            name='tableconfig',
            unique_together=set([('company', 'table', 'dashboard')]),
        ),
    ]
