# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-02 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0008_auto_20170901_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableconfig',
            old_name='table',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='tableconfig',
            unique_together=set([('company', 'name', 'dashboard')]),
        ),
    ]
