# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 17:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0009_auto_20170902_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAdSetConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=128)),
                ('objective', models.CharField(max_length=128)),
                ('optimization_goal', models.CharField(max_length=128)),
                ('billing_event', models.CharField(max_length=128)),
                ('geo', models.CharField(max_length=128)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('optional_config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shsql.Company')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(max_length=256)),
                ('permalink_url', models.URLField(max_length=256)),
                ('accounts', models.ManyToManyField(related_name='fb_images', to='shsql.FacebookAdAccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shsql.Company')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookImageCreative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image_hash', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('body', models.CharField(max_length=512)),
                ('url', models.URLField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shsql.Company')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='facebookimagecreative',
            unique_together=set([('company', 'date_created', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='facebookimage',
            unique_together=set([('company', 'image_hash')]),
        ),
        migrations.AlterUniqueTogether(
            name='facebookadsetconfig',
            unique_together=set([('company', 'platform', 'objective', 'geo')]),
        ),
    ]
