# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-04 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0010_auto_20170903_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookimage',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
