# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-04 18:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0011_facebookimage_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpiconfigs', to='shsql.Company')),
            ],
        ),
        migrations.RenameModel(
            old_name='ReportConfig',
            new_name='FacebookReportConfig',
        ),
        migrations.AlterUniqueTogether(
            name='kpireportconfig',
            unique_together=set([('name', 'company')]),
        ),
    ]
