# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-04 20:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shsql', '0012_auto_20170904_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIBinnedDashboardReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpibinreports', to='shsql.Company')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpibinreports', to='shsql.KPIReportConfig')),
            ],
        ),
        migrations.CreateModel(
            name='KPIDashboardReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField()),
                ('period', models.PositiveSmallIntegerField(default=1)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpidashreports', to='shsql.Company')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='kpidashboardreport',
            unique_together=set([('company', 'report_date', 'period')]),
        ),
        migrations.AlterUniqueTogether(
            name='kpibinneddashboardreport',
            unique_together=set([('company', 'config', 'report_date')]),
        ),
    ]
